const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Chinese",
  "Korean",
  "Japanese",
  "Italian",
  "Portuguese",
  "Arabic",
  "Hindi",
  "Russian",
  "Turkish",
];
const ACTIVITIES = [
  "Wine & Brewery",
  "Events & Festival",
  "Hiking",
  "Cycling",
  "Walking",
  "Museum",
  "Cuisine & Cooking",
  "Dance",
  "Shopping",
  "Rafting",
  "Skydiving",
  "Swimming",
  "Beach & Hotsprings",
  "City Tour",
  "Cultural",
  "4WD",
  "Nature & Wildlife ",
  "Landmarks",
  "Day Trip",
  "Amusement Park",
  "Other Adventure",
];
module.exports = {
  LANGUAGES,
  ACTIVITIES,
};
